
# CRIANDO TABELAS

# CRIANDO A TABELA CLIENTE
CREATE TABLE cliente (
	cli_cpf VARCHAR(11) PRIMARY KEY,
	cli_nome VARCHAR(255) NOT NULL,
	cli_rua VARCHAR(255) NOT NULL,
	cli_numero INT NOT NULL,
	cli_bairro VARCHAR(255) NOT NULL,
	cli_telefone VARCHAR(11) NOT NULL
);

CREATE TABLE categoria (
	cat_codigo INT PRIMARY KEY AUTO_INCREMENT,
	cat_nome VARCHAR(255) NOT NULL UNIQUE
);

# MOSTRA AS CARACTERÍSTICAS DOS ATRIBUTOS DA TABELA
DESCRIBE cliente;
DESCRIBE categoria;

# APAGA UMA TABELA
DROP TABLE cliente;
DROP TABLE categoria;