# MOSTRA A VERSÃO DO BANCO DE DADOS
SELECT VERSION();

# MOSTRA AS INSTÂNCIAS DE BANCOS DISPONÍVEIS
SHOW DATABASES;

# CRIAR UMA INSTÂNCIA DE BANCO DE DADOS
CREATE DATABASE banco;

# APAGAR O BANCO DE DADOS
DROP DATABASE banco;

# CONECTAR A INSTÂNCIA DO BANCO DE DADOS
USE banco;

# MOSTRA TODAS AS TABELAS DO BANCO
SHOW TABLES;

#------------------------------------------------------------------------------------

# CRIANDO TABELAS

# CRIANDO A TABELA CLIENTE
CREATE TABLE cliente (
    cli_cpf INT PRIMARY KEY,
    cli_nome VARCHAR(255) NOT NULL,
    cli_rua VARCHAR(255) NOT NULL,
    cli_numero INT NOT NULL,
    cli_bairro VARCHAR(255) NOT NULL,
    cli_telefone VARCHAR(11) NOT NULL
);

# MOSTRA AS CARACTERÍSTICAS DOS ATRIBUTOS DA TABELA
DESCRIBRE cliente;

# APAGA UMA TABELA
DROP TABLE cliente;