
# SINTAXE INICIAL PARA INTERAGIR COM O BANCO DE DADOS

# MOSTRA A VERSÃO DO BANCO DE DADOS
SELECT VERSION();

# MOSTRA AS INSTÂNCIAS DE BANCOS DISPONÍVEIS
SHOW DATABASES;

# CRIAR UMA INSTÂNCIA DE BANCO DE DADOS
CREATE DATABASE banco;

# CUIDADO !
# APAGAR O BANCO DE DADOS
DROP DATABASE banco;

# CONECTAR A INSTÂNCIA DO BANCO DE DADOS
USE banco;

# MOSTRA TODAS AS TABELAS DO BANCO
SHOW TABLES;